// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;


//Summ.sol
// BIG UPDATE... NEED TO CHANGE IT FROM A DEPOSIT FORMAT TO AN APPROVAL FORMAT. check balance in erc20 THAT THE WALLET HAS X AMOUNT IN ERC ADDRESS AND 
// THEY GAVE APPROVAL FOR THIS CONTRACT TO EXECUTE X AMOUNT FROM THEIR WALLET.... MUCH BETTER... 
